/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** Cryptographich hash types */
@org.apache.avro.specific.AvroGenerated
public enum CryptoHashType {
  MD5, SHA1, SHA256, SHA512, AUTHENTIHASH, SSDEEP, IMPHASH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CryptoHashType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"Cryptographich hash types\",\"symbols\":[\"MD5\",\"SHA1\",\"SHA256\",\"SHA512\",\"AUTHENTIHASH\",\"SSDEEP\",\"IMPHASH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
