/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** * EndMarker records marks the end of a data stream. */
@org.apache.avro.specific.AvroGenerated
public class EndMarker extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8421609828958876276L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EndMarker\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* EndMarker records marks the end of a data stream.\",\"fields\":[{\"name\":\"sessionNumber\",\"type\":\"int\",\"doc\":\"session number in the corresponding StartMarker\"},{\"name\":\"recordCounts\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"doc\":\"* Reports countc of each record type that has been published\\n         * since the the start of the data stream.\",\"order\":\"ignore\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EndMarker> ENCODER =
      new BinaryMessageEncoder<EndMarker>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EndMarker> DECODER =
      new BinaryMessageDecoder<EndMarker>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EndMarker> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EndMarker> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EndMarker>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EndMarker to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EndMarker from a ByteBuffer. */
  public static EndMarker fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** session number in the corresponding StartMarker */
  @Deprecated public int sessionNumber;
  /** * Reports countc of each record type that has been published
         * since the the start of the data stream. */
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> recordCounts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EndMarker() {}

  /**
   * All-args constructor.
   * @param sessionNumber session number in the corresponding StartMarker
   * @param recordCounts * Reports countc of each record type that has been published
         * since the the start of the data stream.
   */
  public EndMarker(java.lang.Integer sessionNumber, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> recordCounts) {
    this.sessionNumber = sessionNumber;
    this.recordCounts = recordCounts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionNumber;
    case 1: return recordCounts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionNumber = (java.lang.Integer)value$; break;
    case 1: recordCounts = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessionNumber' field.
   * @return session number in the corresponding StartMarker
   */
  public java.lang.Integer getSessionNumber() {
    return sessionNumber;
  }

  /**
   * Sets the value of the 'sessionNumber' field.
   * session number in the corresponding StartMarker
   * @param value the value to set.
   */
  public void setSessionNumber(java.lang.Integer value) {
    this.sessionNumber = value;
  }

  /**
   * Gets the value of the 'recordCounts' field.
   * @return * Reports countc of each record type that has been published
         * since the the start of the data stream.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getRecordCounts() {
    return recordCounts;
  }

  /**
   * Sets the value of the 'recordCounts' field.
   * * Reports countc of each record type that has been published
         * since the the start of the data stream.
   * @param value the value to set.
   */
  public void setRecordCounts(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.recordCounts = value;
  }

  /**
   * Creates a new EndMarker RecordBuilder.
   * @return A new EndMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.EndMarker.Builder newBuilder() {
    return new com.bbn.tc.schema.avro.cdm20.EndMarker.Builder();
  }

  /**
   * Creates a new EndMarker RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EndMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.EndMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm20.EndMarker.Builder other) {
    return new com.bbn.tc.schema.avro.cdm20.EndMarker.Builder(other);
  }

  /**
   * Creates a new EndMarker RecordBuilder by copying an existing EndMarker instance.
   * @param other The existing instance to copy.
   * @return A new EndMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.EndMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm20.EndMarker other) {
    return new com.bbn.tc.schema.avro.cdm20.EndMarker.Builder(other);
  }

  /**
   * RecordBuilder for EndMarker instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EndMarker>
    implements org.apache.avro.data.RecordBuilder<EndMarker> {

    /** session number in the corresponding StartMarker */
    private int sessionNumber;
    /** * Reports countc of each record type that has been published
         * since the the start of the data stream. */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> recordCounts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm20.EndMarker.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionNumber)) {
        this.sessionNumber = data().deepCopy(fields()[0].schema(), other.sessionNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.recordCounts)) {
        this.recordCounts = data().deepCopy(fields()[1].schema(), other.recordCounts);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EndMarker instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm20.EndMarker other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sessionNumber)) {
        this.sessionNumber = data().deepCopy(fields()[0].schema(), other.sessionNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.recordCounts)) {
        this.recordCounts = data().deepCopy(fields()[1].schema(), other.recordCounts);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sessionNumber' field.
      * session number in the corresponding StartMarker
      * @return The value.
      */
    public java.lang.Integer getSessionNumber() {
      return sessionNumber;
    }

    /**
      * Sets the value of the 'sessionNumber' field.
      * session number in the corresponding StartMarker
      * @param value The value of 'sessionNumber'.
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.EndMarker.Builder setSessionNumber(int value) {
      validate(fields()[0], value);
      this.sessionNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionNumber' field has been set.
      * session number in the corresponding StartMarker
      * @return True if the 'sessionNumber' field has been set, false otherwise.
      */
    public boolean hasSessionNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sessionNumber' field.
      * session number in the corresponding StartMarker
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.EndMarker.Builder clearSessionNumber() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordCounts' field.
      * * Reports countc of each record type that has been published
         * since the the start of the data stream.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getRecordCounts() {
      return recordCounts;
    }

    /**
      * Sets the value of the 'recordCounts' field.
      * * Reports countc of each record type that has been published
         * since the the start of the data stream.
      * @param value The value of 'recordCounts'.
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.EndMarker.Builder setRecordCounts(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.recordCounts = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'recordCounts' field has been set.
      * * Reports countc of each record type that has been published
         * since the the start of the data stream.
      * @return True if the 'recordCounts' field has been set, false otherwise.
      */
    public boolean hasRecordCounts() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'recordCounts' field.
      * * Reports countc of each record type that has been published
         * since the the start of the data stream.
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.EndMarker.Builder clearRecordCounts() {
      recordCounts = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EndMarker build() {
      try {
        EndMarker record = new EndMarker();
        record.sessionNumber = fieldSetFlags()[0] ? this.sessionNumber : (java.lang.Integer) defaultValue(fields()[0]);
        record.recordCounts = fieldSetFlags()[1] ? this.recordCounts : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EndMarker>
    WRITER$ = (org.apache.avro.io.DatumWriter<EndMarker>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EndMarker>
    READER$ = (org.apache.avro.io.DatumReader<EndMarker>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
