/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** * These types enumerate the types of FileObjects */
@org.apache.avro.specific.AvroGenerated
public enum FileObjectType {
  FILE_OBJECT_BLOCK, FILE_OBJECT_CHAR, FILE_OBJECT_DIR, FILE_OBJECT_FILE, FILE_OBJECT_LINK, FILE_OBJECT_PEFILE, FILE_OBJECT_UNIX_SOCKET  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FileObjectType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* These types enumerate the types of FileObjects\",\"symbols\":[\"FILE_OBJECT_BLOCK\",\"FILE_OBJECT_CHAR\",\"FILE_OBJECT_DIR\",\"FILE_OBJECT_FILE\",\"FILE_OBJECT_LINK\",\"FILE_OBJECT_PEFILE\",\"FILE_OBJECT_UNIX_SOCKET\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
