/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** * The integrity tag may be used to specify the initial integrity of an entity,
     * or to endorse its content after performing appropriate checking/sanitization. */
@org.apache.avro.specific.AvroGenerated
public enum IntegrityTag {
  INTEGRITY_UNTRUSTED, INTEGRITY_BENIGN, INTEGRITY_INVULNERABLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IntegrityTag\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* The integrity tag may be used to specify the initial integrity of an entity,\\n     * or to endorse its content after performing appropriate checking/sanitization.\",\"symbols\":[\"INTEGRITY_UNTRUSTED\",\"INTEGRITY_BENIGN\",\"INTEGRITY_INVULNERABLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
