/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** * These types enumerate the types of IpcObjects */
@org.apache.avro.specific.AvroGenerated
public enum IpcObjectType {
  IPC_OBJECT_PIPE_NAMED, IPC_OBJECT_PIPE_UNNAMED, IPC_OBJECT_SOCKET_ABSTRACT, IPC_OBJECT_SOCKET_PAIR, IPC_OBJECT_SOCKET_PATHNAME, IPC_OBJECT_SOCKET_UNNAMED, IPC_OBJECT_WINDOWS_ALPC, IPC_OBJECT_WINDOWS_MAILSLOT, IPC_OBJECT_SOCKET_NETLINK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IpcObjectType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* These types enumerate the types of IpcObjects\",\"symbols\":[\"IPC_OBJECT_PIPE_NAMED\",\"IPC_OBJECT_PIPE_UNNAMED\",\"IPC_OBJECT_SOCKET_ABSTRACT\",\"IPC_OBJECT_SOCKET_PAIR\",\"IPC_OBJECT_SOCKET_PATHNAME\",\"IPC_OBJECT_SOCKET_UNNAMED\",\"IPC_OBJECT_WINDOWS_ALPC\",\"IPC_OBJECT_WINDOWS_MAILSLOT\",\"IPC_OBJECT_SOCKET_NETLINK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
