/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** * PrincipalType identifies the type of user: either local to the
     * host, or remote users/systems. */
@org.apache.avro.specific.AvroGenerated
public enum PrincipalType {
  PRINCIPAL_LOCAL, PRINCIPAL_REMOTE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PrincipalType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* PrincipalType identifies the type of user: either local to the\\n     * host, or remote users/systems.\",\"symbols\":[\"PRINCIPAL_LOCAL\",\"PRINCIPAL_REMOTE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
