/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;
@SuppressWarnings("all")
/** * */
@org.apache.avro.specific.AvroGenerated
public enum RecordType {
  RECORD_HOST, RECORD_PRINCIPAL, RECORD_PROVENANCE_TAG_NODE, RECORD_UNKNOWN_PROVENANCE_NODE, RECORD_SUBJECT, RECORD_FILE_OBJECT, RECORD_IPC_OBJECT, RECORD_REGISTRY_KEY_OBJECT, RECORD_PACKET_SOCKET_OBJECT, RECORD_NET_FLOW_OBJECT, RECORD_MEMORY_OBJECT, RECORD_SRC_SINK_OBJECT, RECORD_EVENT, RECORD_UNIT_DEPENDENCY, RECORD_TIME_MARKER, RECORD_END_MARKER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RecordType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"*\",\"symbols\":[\"RECORD_HOST\",\"RECORD_PRINCIPAL\",\"RECORD_PROVENANCE_TAG_NODE\",\"RECORD_UNKNOWN_PROVENANCE_NODE\",\"RECORD_SUBJECT\",\"RECORD_FILE_OBJECT\",\"RECORD_IPC_OBJECT\",\"RECORD_REGISTRY_KEY_OBJECT\",\"RECORD_PACKET_SOCKET_OBJECT\",\"RECORD_NET_FLOW_OBJECT\",\"RECORD_MEMORY_OBJECT\",\"RECORD_SRC_SINK_OBJECT\",\"RECORD_EVENT\",\"RECORD_UNIT_DEPENDENCY\",\"RECORD_TIME_MARKER\",\"RECORD_END_MARKER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
