/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm20;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** * TimeMarker records are used to delineate time periods in a data
     * stream to help consumers know their current read position in the
     * data stream. */
@org.apache.avro.specific.AvroGenerated
public class TimeMarker extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8240097057897663180L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TimeMarker\",\"namespace\":\"com.bbn.tc.schema.avro.cdm20\",\"doc\":\"* TimeMarker records are used to delineate time periods in a data\\n     * stream to help consumers know their current read position in the\\n     * data stream.\",\"fields\":[{\"name\":\"tsNanos\",\"type\":\"long\",\"doc\":\"Timestamp in nanoseconds\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TimeMarker> ENCODER =
      new BinaryMessageEncoder<TimeMarker>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TimeMarker> DECODER =
      new BinaryMessageDecoder<TimeMarker>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TimeMarker> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TimeMarker> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TimeMarker>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TimeMarker to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TimeMarker from a ByteBuffer. */
  public static TimeMarker fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Timestamp in nanoseconds */
  @Deprecated public long tsNanos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TimeMarker() {}

  /**
   * All-args constructor.
   * @param tsNanos Timestamp in nanoseconds
   */
  public TimeMarker(java.lang.Long tsNanos) {
    this.tsNanos = tsNanos;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tsNanos;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tsNanos = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tsNanos' field.
   * @return Timestamp in nanoseconds
   */
  public java.lang.Long getTsNanos() {
    return tsNanos;
  }

  /**
   * Sets the value of the 'tsNanos' field.
   * Timestamp in nanoseconds
   * @param value the value to set.
   */
  public void setTsNanos(java.lang.Long value) {
    this.tsNanos = value;
  }

  /**
   * Creates a new TimeMarker RecordBuilder.
   * @return A new TimeMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder newBuilder() {
    return new com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder();
  }

  /**
   * Creates a new TimeMarker RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TimeMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder other) {
    return new com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder(other);
  }

  /**
   * Creates a new TimeMarker RecordBuilder by copying an existing TimeMarker instance.
   * @param other The existing instance to copy.
   * @return A new TimeMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm20.TimeMarker other) {
    return new com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder(other);
  }

  /**
   * RecordBuilder for TimeMarker instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TimeMarker>
    implements org.apache.avro.data.RecordBuilder<TimeMarker> {

    /** Timestamp in nanoseconds */
    private long tsNanos;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tsNanos)) {
        this.tsNanos = data().deepCopy(fields()[0].schema(), other.tsNanos);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TimeMarker instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm20.TimeMarker other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.tsNanos)) {
        this.tsNanos = data().deepCopy(fields()[0].schema(), other.tsNanos);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'tsNanos' field.
      * Timestamp in nanoseconds
      * @return The value.
      */
    public java.lang.Long getTsNanos() {
      return tsNanos;
    }

    /**
      * Sets the value of the 'tsNanos' field.
      * Timestamp in nanoseconds
      * @param value The value of 'tsNanos'.
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder setTsNanos(long value) {
      validate(fields()[0], value);
      this.tsNanos = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tsNanos' field has been set.
      * Timestamp in nanoseconds
      * @return True if the 'tsNanos' field has been set, false otherwise.
      */
    public boolean hasTsNanos() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tsNanos' field.
      * Timestamp in nanoseconds
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm20.TimeMarker.Builder clearTsNanos() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TimeMarker build() {
      try {
        TimeMarker record = new TimeMarker();
        record.tsNanos = fieldSetFlags()[0] ? this.tsNanos : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TimeMarker>
    WRITER$ = (org.apache.avro.io.DatumWriter<TimeMarker>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TimeMarker>
    READER$ = (org.apache.avro.io.DatumReader<TimeMarker>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
