/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EDGE_LABELS {
  modified, wasAssociatedWith, generated, read, actedOn, wasGeneratedBy  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EDGE_LABELS\",\"namespace\":\"com.bbn.tc.schema.avro\",\"symbols\":[\"modified\",\"wasAssociatedWith\",\"generated\",\"read\",\"actedOn\",\"wasGeneratedBy\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
