/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NODE_LABELS {
  unitOfExecution, artifact, agent  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NODE_LABELS\",\"namespace\":\"com.bbn.tc.schema.avro\",\"symbols\":[\"unitOfExecution\",\"artifact\",\"agent\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
